### ISSUE TITLE
Expose home-manager module

### ISSUE THREAD

**Issue by elythh** [GaetanLepage/kickstart.nixvim#1]
Hello, I'm still very bad at nix and I was wondering how can I pass the home-manager module out of my flake ?
The goal is to import my flake containing my nixvim configuration into my NixOS  config byt also be able to modify it there directly using home-manager.

EDIT: This is poorly explained so here's my current flake for more context
https://github.com/elythh/nixvim/blob/main/flake.nix

**Comment by MattSturgeon** [comment]
This isn't really the right place to be asking usage questions. [nixvim discussions] or the [matrix chat](https://matrix.to/#/#nixvim:matrix.org) would be better.

It sounds like what you want is to build a "standalone" nixvim and then extend it in your other configs using `nixvimExtend`.

See the [Standalone installation instructions](https://nix-community.github.io/nixvim/user-guide/install.html#standalone-usage) and the [Standalone Usage](https://nix-community.github.io/nixvim/modules/standalone.html) guide.

[nixvim discussions]:https://github.com/nix-community/nixvim/discussions

**Comment by elythh** [comment]
My bad, thanks for pointing me in the right direction !
